FERIA.FRONT/Controllers/ProductorController.cs
using FERIA.CLASES;
using FERIA.FRONT.NEGOCIO;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace FERIA.FRONT.Controllers
{
    [Authorize(Roles = "2")]
    public class ProductorController : Controller
    {

        ServicioProducto servicioProducto;
        ServicioProceso servicioProceso;
        Usuario Login = Helper.Autenticacion.TraerUsuarioAutenticado();
        public ProductorController()
        {
            servicioProducto = new ServicioProducto();
            servicioProceso = new ServicioProceso();
        }
        // GET: Productor
        public ActionResult Listar(string mensaje = "")
        {
            if (!string.IsNullOrEmpty(mensaje))
            {
                ViewBag.Exito = false;
                ViewBag.Mensaje = mensaje;
            }

            var respuesta = servicioProducto.Listar(Login.IdUsuario, Login.SesionId);
            if (respuesta.Exito)
                return View(respuesta.Productos);
            else
            {
                ViewBag.Mensaje = respuesta.Mensaje;
                ViewBag.Exito = respuesta.Exito;
                return View(new List<Producto>());
            }
        }

        public ActionResult Mantener(int id = 0)
        {
            if (id != 0)
            {
                var respuesta = servicioProducto.Leer(id, Login.SesionId);
                if (!respuesta.Exito)
                {
                    return RedirectToAction("Listar", new { respuesta.Mensaje });
                }
                return View(respuesta.Producto);
            }
            else
            {
                return View(new Producto());
            }
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Mantener(Producto producto)
        {   
            if (producto.IdProducto == 0)
            {
                producto.IdUsuario = Login.IdUsuario;
                var respuesta = servicioProducto.Crear(producto, Login.SesionId);
                ViewBag.Exito = respuesta.Exito;
                ViewBag.Mensaje = respuesta.Mensaje;
                if (!ViewBag.Exito)
                    return View(producto);
                return View(respuesta.Producto);
            }
            else
            {
                var respuesta = servicioProducto.Modificar(producto, Login.SesionId);
                ViewBag.Exito = respuesta.Exito;
                ViewBag.Mensaje = respuesta.Mensaje;
                if (!ViewBag.Exito)
                    return View(producto);

                return View(respuesta.Producto);
            }
        }




    }
}

FERIA.FRONT/Controllers/SistemaController.cs
using FERIA.CLASES;
using FERIA.FRONT.NEGOCIO;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace FERIA.FRONT.Controllers
{
    [Authorize]
    public class SistemaController : Controller
    {
        ServicioUsuario servicioUsuario;
        Usuario Login = Helper.Autenticacion.TraerUsuarioAutenticado();
        public SistemaController() {
            servicioUsuario = new ServicioUsuario();
        }

        // GET: Sistema
        public ActionResult Index()
        {
            return View();
        }
        [AllowAnonymous]
        public ActionResult CerrarSesion()
        {
            Helper.Autenticacion.DestruirSesionUsuario();
            return RedirectToAction("Login", "Home", new { cerrarSesion = true });
        }
        #region "PERFILES"
        public ActionResult Perfil(bool exito = false, bool error = false, string mensaje = "")
        {
            ViewBag.Exito = exito;
            ViewBag.Error = error;
            ViewBag.Mensaje = mensaje;
            var respuesta = servicioUsuario.Leer(Login.IdUsuario, Login.SesionId );
            if (exito)
            {
                respuesta.Usuario.SesionId = Login.SesionId;
                Helper.Autenticacion.Login(respuesta.Usuario);
            }
            return View(respuesta.Usuario);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Perfil(Usuario usuario)
        {
            if (!string.IsNullOrEmpty(usuario.Clave))
            {
                usuario.Clave = "";
            }

            var respuesta = servicioUsuario.Modificar(usuario, Login.SesionId);
            if (respuesta.Exito)
            {
                ViewBag.Exito = true;
                ViewBag.Mensaje = "Se ha modificado correctamente";
            }
            else
            {
                ViewBag.Error = true;
                ViewBag.Mensaje = respuesta.Mensaje;
            }
            return RedirectToAction("Perfil", new { exito = ViewBag.Exito, error = ViewBag.Error, mensaje = ViewBag.Mensaje });

        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult PerfilClave(Usuario usuario)
        {

            usuario.Clave = NEGOCIO.Funciones.Encripta.EncodePassword(usuario.Clave);
            usuario.ReClave = NEGOCIO.Funciones.Encripta.EncodePassword(usuario.ReClave);

            var respuesta = servicioUsuario.ModificarClave(usuario, Login.SesionId);
            if (respuesta.Exito)
            {
                ViewBag.Exito = true;
                ViewBag.Mensaje = "Se ha modificado la clave correctamente";
            }
            else
            {
                ViewBag.Error = true;
                ViewBag.Mensaje = respuesta.Mensaje;
            }
            return RedirectToAction("Perfil", new { exito = ViewBag.Exito, error = ViewBag.Error, mensaje = ViewBag.Mensaje });
        }
        #endregion
    }
}

FERIA.FRONT/Views/Productor/Listar.cshtml
@model List<FERIA.CLASES.Producto>
@{
    Layout = "~/Views/Shared/_Interno.cshtml";
    if (ViewBag.Exito == null)
    {
        ViewBag.Exito = false;
    }
    if (ViewBag.Mensaje == null)
    {
        ViewBag.Mensaje = "";
    }
}
<div class="row wrapper border-bottom white-bg page-heading">
    <div class="col-lg-10">
        <h2>Mis Productos</h2>
        <ol class="breadcrumb">
            <li class="breadcrumb-item">
                <a href="@Url.Action("Index", "Sistema")">Inicio</a>
            </li>
            @*<li class="breadcrumb-item">
                    <a>Forms</a>
                </li>*@
            <li class="breadcrumb-item active">
                <strong>Listado</strong>
            </li>
        </ol>
    </div>
    <div class="col-lg-2">

    </div>
</div>
<div class="wrapper wrapper-content animated fadeInRight">
    <div class="row">
        <div class="col-lg-12">
            <!--GRILLA DE RESULTADOS-->
            <div class="row">
                <div class="col-lg-12">
                    <button class="btn btn-primary pull-right" type="button" onclick="location.href = '@Url.Action("Mantener", "Productor")'; return false;"><i class="fa fa-plus"></i> <span class="bold">Nuevo Producto</span></button>
                    @if (Model.Count > 0)
                    {
                        <div class="ibox ">
                            <div class="ibox-title">
                                <h5>Resultado de Búsqueda </h5>
                            </div>
                            <div class="ibox-content">
                                <table class="table table-striped table-responsive-lg">
                                    <thead>
                                        <tr>
                                            <th>#</th>
                                            <th>Código Producto</th>
                                            <th>Nombre</th>
                                            <th>Categoria</th>
                                            <th>Stock</th>
                                            <th>Valor (KG)</th>
                                            <th>Calidad</th>
                                            <th>Fecha Caducidad</th>
                                            <th>Accion</th>
                                        </tr>
                                    </thead>
                                    <tbody>
                                        @foreach (FERIA.CLASES.Producto item in Model)
                                        {
                                        <tr>
                                            <td>@item.IdProducto </td>
                                            <td>@item.CodigoProducto </td>
                                            <td>@item.Nombre </td>
                                            <td>@item.Categoria.NombreCategoria </td>
                                            <td>@item.Stock </td>
                                            <td>@item.ValorUnitario </td>
                                            <td>@item.Calidad <i class="fa fa-star"></i></td>
                                            <td>@item.FechaCaducidad.ToString("dd-MM-yyyy") </td>
                                            <td>
                                                <button class="btn btn-default btn-circle" title="Editar" type="button" onclick="location.href = '@Url.Action("Mantener", "Productor", new { id = item.IdProducto })'; return false;">
                                                    <i class="fa fa-edit "></i>
                                                </button>
                                            </td>
                                        </tr>
                                        }
                                    </tbody>
                                </table>
                            </div>
                        </div>
                    }
                    else
                    {
                        <div class="ibox-content">
                            <div class="alert alert-info">
                                No existen Datos
                            </div>
                        </div>
                    }
                </div>
            </div>
        </div>
    </div>
</div>
@section Scripts{
    @if (ViewBag.Mensaje != "")
    {
        <script>
        swal({
            title: ("@ViewBag.Exito" != "False") ? "Felicidades!" :"Error!",
            text: fncReemplazaTilde("@ViewBag.Mensaje"),
            type: ("@ViewBag.Exito" != "False") ? "success" :"error"
        });
        </script>
    }
}

FERIA.FRONT/Views/Productor/Mantener.cshtml
@model FERIA.CLASES.Producto
@{
    ViewBag.Title = "Mantención de Productos";
    Layout = "~/Views/Shared/_Interno.cshtml";

    //var Login = FERIA.FRONT.Helper.Autenticacion.TraerUsuarioAutenticado();

    ViewBag.Title = (Model.IdProducto == 0) ? "Creación de Producto" : "Modificación de Producto";
    ViewBag.Accion = (Model.IdProducto == 0) ? "Grabar" : "Modificar";



    if (ViewBag.Exito == null)
    {
        ViewBag.Exito = false;
    }
    if (ViewBag.Mensaje == null)
    {
        ViewBag.Mensaje = "";
    }
}
<div class="row wrapper border-bottom white-bg page-heading">
    <div class="col-lg-10">
        <h2>Productor</h2>
        <ol class="breadcrumb">
            <li class="breadcrumb-item">
                <a href="@Url.Action("Index", "Sistema")">Inicio</a>
            </li>
            <li class="breadcrumb-item">
                <a>Producto</a>
            </li>
            <li class="breadcrumb-item active">
                <strong>@ViewBag.Title</strong>
            </li>
        </ol>
    </div>
    <div class="col-lg-2">

    </div>
</div>
<div class="wrapper wrapper-content animated fadeInRight">
    <div class="row">
        <div class="col-lg-12">
            <form role="form" method="post" action="@Url.Action("Mantener", "Productor")" autocomplete="off">
                @Html.AntiForgeryToken()
                <input type="hidden" name="IdProducto" id="IdProducto" value="@Model.IdProducto" />
                <input type="hidden" name="IdUsuario" id="IdUsuario" value="@Model.IdUsuario" />
                <div class="row">
                    <div class="col-lg-12">
                        <div class="ibox ">
                            <div class="ibox-title">
                                <h5>@ViewBag.Title</h5>
                            </div>
                            <div class="ibox-content">
                                <div class="row">
                                    <div class="col-sm-12">
                                        <h3 class="m-t-none m-b">Datos Producto</h3>
                                        <p>Información del Producto</p>
                                        <div class="form-row">
                                            <div class="form-group col-lg-4">
                                                <label>Nombre Producto</label>
                                                <input type="text" name="Nombre" id="Nombre" placeholder="Ingrese Nombre Producto" class="form-control" value="@Model.Nombre" required />
                                            </div>
                                            <div class="form-group col-lg-4">
                                                <label>Código Producto</label>
                                                <input type="text" name="CodigoProducto" id="CodigoProducto" placeholder="Ingrese Código Producto" class="form-control" value="@Model.CodigoProducto" required />
                                            </div>
                                            <div class="form-group col-lg-4">
                                                <label>Categoria</label>
                                                <select name="IdCategoria" id="IdCategoria" class="form-control" required>
                                                    <option value="">Seleccione</option>
                                                    @foreach (var item in new FERIA.FRONT.NEGOCIO.ServicioUtil().Categorias())
                                                    {
                                                        <option value="@item.IdCategoria" @((item.IdCategoria.Equals(Model.IdCategoria) ? "selected" : ""))>@item.NombreCategoria (@item.NombreIngles)</option>
                                                    }
                                                </select>
                                            </div>
                                        </div>
                                        <div class="form-row">
                                            <div class="form-group col-lg-4">
                                                <label>Valor Unitario(KG)</label>
                                                <input type="Number" name="ValorUnitario" id="ValorUnitario" placeholder="Ingrese valor unitario" min="1" max="99999" class="form-control" value="@Model.ValorUnitario" required />
                                            </div>
                                            <div class="form-group col-lg-4">
                                                <label>Stock Producto</label>
                                                <input type="Number" name="Stock" id="Stock" placeholder="Ingrese cantidad disponible(KG)" min="1" max="99999" class="form-control" value="@Model.Stock" required />
                                            </div>
                                            <div class="form-group col-lg-4">
                                                <label>Calidad <i class="fa fa-star"></i></label>
                                                <input type="Number" name="Calidad" id="Calidad" placeholder="Ingrese calidad 1 a 5" min="1" max="5" class="form-control" value="@Model.Calidad" required />
                                            </div>
                                        </div>
                                        <div class="form-row">
                                            <div class="form-group col-lg-4">
                                                <label>Tipo Venta</label>
                                                <select name="TipoVenta" id="TipoVenta" class="form-control" required>
                                                    <option value="">Seleccione</option>
                                                    @foreach (var item in new FERIA.FRONT.NEGOCIO.ServicioUtil().TipoVenta())
                                                    {
                                                        <option value="@item" @((item.Equals(Model.TipoVenta) ? "selected" : ""))>@item</option>
                                                    }
                                                </select>
                                            </div>
                                            <div class="form-group col-lg-4">
                                                <label>Fecha Caducidad</label>
                                                <input type="date" name="FechaCaducidad" id="FechaCaducidad" placeholder="Ingrese Fecha Caducidad" min="1" max="5" class="form-control" value="@((Model.FechaCaducidad == DateTime.MinValue) ? "" : Model.FechaCaducidad.ToString("yyyy-MM-dd"))" required />
                                            </div>
                                        </div>
                                        <div class="form-row">
                                            <div class="form-group col-lg-12">
                                                <label>Descripción</label>
                                                <textarea name="Descripcion" id="Descripcion" cols="50" rows="4" placeholder="Ingrese Descripción" class="form-control">@Model.Descripcion</textarea>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                                <div class="row">
                                    <div class="col-sm-12">
                                        <div class=" pull-right ">
                                            <button class="btn btn-default" type="button" onclick="location.href = '@Url.Action("Listar", "Productor")';"><i class="fa fa-backward"></i><span class="bold"> Volver</span></button>
                                            <button class="btn btn-primary" type="submit"><i class="fa fa-save"></i><span class="bold"> @ViewBag.Accion</span></button>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </form>
        </div>
    </div>
</div>

@section Scripts{
    @if (ViewBag.Mensaje != "")
    {
        <script>
        swal({
            title: ("@ViewBag.Exito" != "False") ? "Felicidades!" :"Error!",
            text: fncReemplazaTilde("@ViewBag.Mensaje"),
            type: ("@ViewBag.Exito" != "False") ? "success" :"error"
        });
        </script>
    }

}