FERIA.FRONT/Controllers/ClienteController.cs
using FERIA.CLASES;
using FERIA.FRONT.NEGOCIO;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace FERIA.FRONT.Controllers
{
    [Authorize(Roles = "3,4")]
    public class ClienteController : Controller
    {
        ServicioOrden servicioOrden;
        Usuario Login = Helper.Autenticacion.TraerUsuarioAutenticado();
        public ClienteController() 
        {
            servicioOrden = new ServicioOrden();
        }

        // GET: Cliente
        public ActionResult Index(string mensaje="")
        {
            if (!string.IsNullOrEmpty(mensaje))
            {
                ViewBag.Exito = false;
                ViewBag.Mensaje = mensaje;
            }

            var respuesta = servicioOrden.Listar(Login.IdUsuario, Login.SesionId);
            if (respuesta.Exito)
                return View(respuesta.Ordenes);
            else
            {                
                ViewBag.Mensaje = respuesta.Mensaje;
                ViewBag.Exito = respuesta.Exito;
                return View(new List<Orden>());
            }
        }

        public ActionResult Mantener(int id = 0)
        {
            if (id != 0)
            {
                var respuesta = servicioOrden.Leer(id, Login.SesionId  );
                if (!respuesta.Exito)
                {
                    return RedirectToAction("Index", new { respuesta.Mensaje });
                }
                return View(respuesta.Orden);
            }
            else
            {
                return View(new Orden());
            }
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Mantener(Orden orden)
        {
            if (Login.IdPerfil == (int)TipoPerfil.Cliente_Externo) {
                orden.IdClienteExterno = Login.IdUsuario;
            }
            if (Login.IdPerfil == (int)TipoPerfil.Cliente_Interno)
            {
                orden.IdClienteInterno = Login.IdUsuario ;
            }

            if (orden.IdOrden== 0)
            {
                var respuesta = servicioOrden.Crear(orden, Login.SesionId);
                ViewBag.Exito = respuesta.Exito;
                ViewBag.Mensaje = respuesta.Mensaje;
                if (!ViewBag.Exito)
                    return View(orden);
                return View(respuesta.Orden);
            }
            else
            {
                var respuesta = servicioOrden.Modificar(orden, Login.SesionId);
                ViewBag.Exito = respuesta.Exito;
                ViewBag.Mensaje = respuesta.Mensaje;
                if (!ViewBag.Exito)
                    return View(orden);

                return View(respuesta.Orden);
            }
        }

    }
}

FERIA.FRONT/Controllers/SistemaController.cs
using FERIA.CLASES;
using FERIA.FRONT.NEGOCIO;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace FERIA.FRONT.Controllers
{
    [Authorize]
    public class SistemaController : Controller
    {
        ServicioUsuario servicioUsuario;
        Usuario Login = Helper.Autenticacion.TraerUsuarioAutenticado();
        public SistemaController() {
            servicioUsuario = new ServicioUsuario();
        }

        // GET: Sistema
        public ActionResult Index()
        {
            return View();
        }
        [AllowAnonymous]
        public ActionResult CerrarSesion()
        {
            Helper.Autenticacion.DestruirSesionUsuario();
            return RedirectToAction("Login", "Home", new { cerrarSesion = true });
        }
        #region "PERFILES"
        public ActionResult Perfil(bool exito = false, bool error = false, string mensaje = "")
        {
            ViewBag.Exito = exito;
            ViewBag.Error = error;
            ViewBag.Mensaje = mensaje;
            var respuesta = servicioUsuario.Leer(Login.IdUsuario, Login.SesionId );
            if (exito)
            {
                respuesta.Usuario.SesionId = Login.SesionId;
                Helper.Autenticacion.Login(respuesta.Usuario);
            }
            return View(respuesta.Usuario);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Perfil(Usuario usuario)
        {
            if (!string.IsNullOrEmpty(usuario.Clave))
            {
                usuario.Clave = "";
            }

            var respuesta = servicioUsuario.Modificar(usuario, Login.SesionId);
            if (respuesta.Exito)
            {
                ViewBag.Exito = true;
                ViewBag.Mensaje = "Se ha modificado correctamente";
            }
            else
            {
                ViewBag.Error = true;
                ViewBag.Mensaje = respuesta.Mensaje;
            }
            return RedirectToAction("Perfil", new { exito = ViewBag.Exito, error = ViewBag.Error, mensaje = ViewBag.Mensaje });

        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult PerfilClave(Usuario usuario)
        {

            usuario.Clave = NEGOCIO.Funciones.Encripta.EncodePassword(usuario.Clave);
            usuario.ReClave = NEGOCIO.Funciones.Encripta.EncodePassword(usuario.ReClave);

            var respuesta = servicioUsuario.ModificarClave(usuario, Login.SesionId);
            if (respuesta.Exito)
            {
                ViewBag.Exito = true;
                ViewBag.Mensaje = "Se ha modificado la clave correctamente";
            }
            else
            {
                ViewBag.Error = true;
                ViewBag.Mensaje = respuesta.Mensaje;
            }
            return RedirectToAction("Perfil", new { exito = ViewBag.Exito, error = ViewBag.Error, mensaje = ViewBag.Mensaje });
        }
        #endregion
    }
}

FERIA.FRONT/Views/Cliente/Index.cshtml
@model List<FERIA.CLASES.Orden>
@{
    Layout = "~/Views/Shared/_Interno.cshtml";
    if (ViewBag.Exito == null)
    {
        ViewBag.Exito = false;
    }
    if (ViewBag.Mensaje == null)
    {
        ViewBag.Mensaje = "";
    }
}
<div class="row wrapper border-bottom white-bg page-heading">
    <div class="col-lg-10">
        <h2>Ordenes</h2>
        <ol class="breadcrumb">
            <li class="breadcrumb-item">
                <a href="@Url.Action("Index", "Sistema")">Inicio</a>
            </li>
            @*<li class="breadcrumb-item">
                    <a>Forms</a>
                </li>*@
            <li class="breadcrumb-item active">
                <strong>Listado</strong>
            </li>
        </ol>
    </div>
    <div class="col-lg-2">

    </div>
</div>
<div class="wrapper wrapper-content animated fadeInRight">
    <div class="row">
        <div class="col-lg-12">            
            <!--GRILLA DE RESULTADOS-->
            <div class="row">
                <div class="col-lg-12">
                    <button class="btn btn-primary pull-right" type="button" onclick="location.href = '@Url.Action("Mantener", "Cliente")'; return false;"><i class="fa fa-plus"></i> <span class="bold">Nueva Orden</span></button>
                    @if (Model.Count > 0)
                    {
                        <div class="ibox ">
                            <div class="ibox-title">
                                <h5>Resultado de Búsqueda </h5>
                            </div>
                            <div class="ibox-content">
                                <table class="table table-striped table-responsive-lg">
                                    <thead>
                                        <tr>
                                            <th>#</th>
                                            <th>Precio Venta ($)</th>
                                            <th>Fecha</th>
                                            <th>Firmó</th>
                                            <th>Fecha Firma</th>
                                            <th>Cantidad Detalle</th>
                                            <th>Estado</th>
                                            <th>Accion</th>
                                        </tr>
                                    </thead>
                                    <tbody>
                                        @foreach (FERIA.CLASES.Orden  item in Model)
                                        {
                                            string fechafirma = "-";
                                            if (item.FirmaContrato) {
                                                fechafirma = ((item.FechaFirmaContrato.Equals(DateTime.MinValue)) ? "-" : item.FechaFirmaContrato.ToString("dd-MM-yyyy"));
                                            }
                                        <tr>
                                            <td>@item.IdOrden </td>
                                            <td align="right">@item.PrecioVenta.ToString("#0,00") </td>
                                            <td>@item.FechaOrden.ToString("dd-MM-yyyy")</td>
                                            <td>@((item.FirmaContrato)?"SI":"NO") </td>
                                            <td>@fechafirma</td>
                                            <td>@item.DetalleOrden.Count </td>
                                            <td>@item.Estado  </td>
                                            <td>
                                                @if (item.Estado.Equals("PENDIENTE"))
                                                {
                                                    <button class="btn btn-default btn-circle" title="Editar Bus" type="button" onclick="location.href = '@Url.Action("Mantener", "Cliente", new { id = item.IdOrden })'; return false;">
                                                        <i class="fa fa-edit "></i>
                                                    </button>
                                                }
                                            </td>
                                        </tr>
                                        }
                                    </tbody>
                                </table>
                            </div>
                        </div>
                    }
                    else
                    {
                        <div class="ibox-content">
                            <div class="alert alert-info">
                                No existen Datos
                            </div>
                        </div>
                    }
                </div>
            </div>
        </div>
    </div>
</div>
@section Scripts{   
    @if (ViewBag.Mensaje != "")
    {
        <script>
        swal({
            title: ("@ViewBag.Exito" != "False") ? "Felicidades!" :"Error!",
            text: fncReemplazaTilde("@ViewBag.Mensaje"),
            type: ("@ViewBag.Exito" != "False") ? "success" :"error"
        });
        </script>
    }
}

FERIA.FRONT/Views/Cliente/Mantener.cshtml
@model FERIA.CLASES.Orden
@{
    ViewBag.Title = "Mantención de Ordenes";
    Layout = "~/Views/Shared/_Interno.cshtml";

    //var Login = FERIA.FRONT.Helper.Autenticacion.TraerUsuarioAutenticado();

    ViewBag.Title = (Model.IdOrden == 0) ? "Creación de Orden" : "Modificación de Orden";
    ViewBag.Accion = (Model.IdOrden == 0) ? "Grabar" : "Modificar";



    if (ViewBag.Exito == null)
    {
        ViewBag.Exito = false;
    }
    if (ViewBag.Mensaje == null)
    {
        ViewBag.Mensaje = "";
    }
}
<div class="row wrapper border-bottom white-bg page-heading">
    <div class="col-lg-10">
        <h2>Cliente</h2>
        <ol class="breadcrumb">
            <li class="breadcrumb-item">
                <a href="@Url.Action("Index", "Sistema")">Inicio</a>
            </li>
            <li class="breadcrumb-item">
                <a>Órdenes</a>
            </li>
            <li class="breadcrumb-item active">
                <strong>@ViewBag.Title</strong>
            </li>
        </ol>
    </div>
    <div class="col-lg-2">

    </div>
</div>
<div class="wrapper wrapper-content animated fadeInRight">
    <div class="row">
        <div class="col-lg-12">
            <form role="form" method="post" action="@Url.Action("Mantener", "Cliente")" autocomplete="off">
                @Html.AntiForgeryToken()
                <input type="hidden" name="IdOrden" id="IdOrden" value="@Model.IdOrden" />
                <div class="row">
                    <div class="col-lg-12">
                        <div class="ibox ">
                            <div class="ibox-title">
                                <h5>@ViewBag.Title</h5>
                            </div>
                            <div class="ibox-content">
                                <div class="row">
                                    <div class="col-sm-12">
                                        <h3 class="m-t-none m-b">Datos Orden</h3>
                                        <p>Información de la Orden</p>
                                        <div class="form-row">
                                            <div class="form-group col-lg-4">
                                                <label>Precio Orden ($ PESOS) <i class="fa fa-money"></i></label>
                                                <input type="number" name="PrecioVenta" id="PrecioVenta" placeholder="Ingrese precio compra" class="form-control" value="@Model.PrecioVenta" required />
                                            </div>
                                        </div>
                                        <p>Detalle de la Orden &nbsp;<small><a class="text-success" data-toggle="modal" href="#modal-form-detalle" onclick="limpiarModal()"><i class="fa fa-plus-square"></i><span class="bold"> Agregar</span></a></small></p>
                                        <div id="dvDetalle">
                                            @if (!Model.IdOrden.Equals(0))
                                            {
                                                int ix = 0;
                                                <div class="row">
                                                    <div class="col-sm-4"><label><b>Categoria</b></label></div>
                                                    <div class="col-sm-4"><label><b>Cantidad</b></label></div>
                                                    <div class="col-sm-4"><label>&nbsp;</label></div>
                                                </div>
                                                foreach (var item in Model.DetalleOrden)
                                                {
                                                    <div class="row">
                                                        <div class="col-sm-4"><label>@item.NombreCategoria (@item.NombreIngles)<input type="hidden" name="DetalleOrden[@ix].IdCategoria" value="@item.IdCategoria" /><input type="hidden" name="DetalleOrden[@ix].NombreCategoria" value="@item.NombreCategoria" /></label></div>
                                                        <div class="col-sm-4"><label>@item.Cantidad<input type="hidden" name="DetalleOrden[@ix].Cantidad" value="@item.Cantidad"></label></div>
                                                        <div class="col-sm-4">
                                                            <button class="btn btn-default btn-circle bg-danger" title="Eliminar detalle" type="button" onclick="fncEliminaDetalle('@item.IdCategoria');">
                                                                <i class="fa fa-trash"></i>
                                                            </button>
                                                        </div>
                                                    </div>
                                                    ix++;
                                                }
                                            }
                                        </div>
                                    </div>
                                </div>
                                <div class="row">
                                    <div class="col-sm-12">
                                        <div class=" pull-right ">
                                            <button class="btn btn-default" type="button" onclick="location.href = '@Url.Action("Index", "Cliente")';"><i class="fa fa-backward"></i><span class="bold"> Volver</span></button>
                                            <button class="btn btn-primary" type="submit"><i class="fa fa-save"></i><span class="bold"> @ViewBag.Accion</span></button>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </form>
        </div>
    </div>
</div>

<div id="modal-form-detalle" class="modal" style="z-index:10000!important;" aria-hidden="true" tabindex="-1">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-body">
                <div class="row">
                    <div class="col-lg-12 col-md-12 col-xs-12 col-sm-12">
                        <div class="wrapperMap">
                            <div class="containerMap">
                                <h3 class="m-t-none m-b">Categorias</h3>
                                <p>Agregar Detalle</p>
                                <div class="form-row">
                                    <div class="form-group col-lg-12">
                                        <label>Categoria</label>
                                        <select name="categoria" id="categoria" class="form-control" required>
                                            <option value="">Seleccione</option>
                                            @foreach (var item in new FERIA.FRONT.NEGOCIO.ServicioUtil().Categorias())
                                            {
                                                <option value="@item.IdCategoria">@item.NombreCategoria (@item.NombreIngles)</option>
                                            }
                                        </select>
                                    </div>
                                </div>
                                <div class="form-row">
                                    <div class="form-group col-lg-12">
                                        <label>Cantidad (KG)</label>
                                        <input type="number" name="cantidad" id="cantidad" maxlength="20" placeholder="Ingrese cantidad" min="1" max="99999" class="form-control" value="0" required />
                                    </div>
                                </div>
                                <div class="form-row">
                                    <div class="col-lg-12 col-md-12 col-xs-12 col-sm-12">
                                        <div class="pull-right ">
                                            <button class="btn btn-default" type="button" data-dismiss="modal"><i class="fa fa-close"></i><span class="bold">Cerrar</span></button>
                                            <button class="btn btn-primary" type="submit" id="btnGrabarDetalle"><i class="fa fa-save"></i><span class="bold"> Grabar</span></button>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

@section Scripts{
    <script>
        var detalle = [];
        $(document).ready(function () {
            $("#btnGrabarDetalle").click(function () {
                if ($("#categoria").val() == "") {
                    Mensaje("Seleccione una cetegoría", "False");
                    return false;
                }
                if ($("#cantidad").val() == "") {
                    Mensaje("Ingresa una cantidad", "False");
                    return false;
                }
                else {
                    if ($("#cantidad").val() == 0) {
                        Mensaje("Cantidad debe ser superior a 0", "False");
                        return false;
                    }
                }
                det = $("#categoria").val() + "|" + $("#cantidad").val() + "|" + $("#categoria option:selected").text();
                detalle.forEach(function (deta, index) {
                    if (deta.split("|")[0] == $("#categoria").val()) {
                        Mensaje("Categoría ya fue ingresada, seleccione otra u eliminela y cambie cantidad", "False");
                        det = "";
                        return false;
                    }
                });
                if (det != "") {
                    detalle.push(det);
                }
                ArmarDetalle();
                $("#modal-form-detalle").modal('toggle');

            });
        });

        function fncEliminaDetalle(vCat) {
            var newDetalle = [];
            detalle.forEach(function (deta, index) {
                if (deta.split("|")[0] != vCat) {
                    newDetalle.push(deta);
                }
            });
            detalle = newDetalle;
            ArmarDetalle();

        }
        function ArmarDetalle() {
            var htmlRev = "<div class=\"row\">" +
                "<div class=\"col-sm-4\"><label><b>Categoria</b></label></div> " +
                "<div class=\"col-sm-4\"><label><b>Cantidad</b></label></div> " +
                "<div class=\"col-sm-4\"><label>&nbsp;</label></div> " +
                "</div>";
            detalle.forEach(function (deta, index) {
                dato = deta.split("|");
                htmlRev += "<div class=\"row\">" +
                    "<div class=\"col-sm-4\"><label>" + dato[2] + "<input type=\"hidden\" name=\"DetalleOrden[" + index + "].IdCategoria\" value=\"" + dato[0] + "\" /><input type=\"hidden\" name=\"DetalleOrden[" + index + "].NombreCategoria\" value=\"" + dato[2] + "\" /></label></div> " +
                    "<div class=\"col-sm-4\"><label>" + dato[1] + "<input type=\"hidden\" name=\"DetalleOrden[" + index + "].Cantidad\" value=\"" + dato[1] + "\"></label></div> " +
                    "<div class=\"col-sm-4\"><button class=\"btn btn-default btn-circle bg-danger\" title=\"Eliminar detalle\" type=\"button\" onclick=\"fncEliminaDetalle('" + dato[0] + "');\">" +
                    "<i class=\"fa fa-trash\"></i>" +
                    "</button></div> " +
                    "</div>"
            });
            $("#dvDetalle").html(htmlRev);

        }
        function limpiarModal() {
            $("#categoria").val("");
            $("#cantidad").val("0");
        }
        function Mensaje(strMensaje, exito) {
            swal({
                title: (exito != "False") ? "Felicidades!" : "Error!",
                text: fncReemplazaTilde(strMensaje),
                type: (exito != "False") ? "success" : "error"
            });
        }
    </script>
    @if (!Model.IdOrden.Equals(0))
    {
        <script>
            $(document).ready(function () {
                @foreach(FERIA.CLASES.DetalleOrden item in Model.DetalleOrden)
                {
                    @Html.Raw("detalle.push('" + string.Concat(item.IdCategoria, "|", item.Cantidad, "|", item.NombreCategoria, "("+ item.NombreIngles +")") + "');");
                }
            });
        </script>
    }
    @if (ViewBag.Mensaje != "")
    {
        <script>
        swal({
            title: ("@ViewBag.Exito" != "False") ? "Felicidades!" :"Error!",
            text: fncReemplazaTilde("@ViewBag.Mensaje"),
            type: ("@ViewBag.Exito" != "False") ? "success" :"error"
        });
        </script>
    }

}