FERIA.FRONT/Controllers/CamionController.cs
using FERIA.CLASES;
using FERIA.FRONT.NEGOCIO;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace FERIA.FRONT.Views
{
    [Authorize(Roles = "5")]
    public class CamionController : Controller
    {
        ServicioTransportista servicioTransportista;
        Usuario Login = Helper.Autenticacion.TraerUsuarioAutenticado();
        public CamionController()
        {
            servicioTransportista = new ServicioTransportista();
        }
        // GET: Camion
        public ActionResult Listar(string mensaje = "", bool exito = false)
        {
            if (!string.IsNullOrEmpty(mensaje))
            {
                ViewBag.Exito = exito;
                ViewBag.Mensaje = mensaje;
            }
            var respuesta = servicioTransportista.ListarCamiones(Login.IdUsuario, Login.SesionId);
            if (respuesta.Exito)
                return View(respuesta.Camiones);
            else
            {
                ViewBag.Mensaje = respuesta.Mensaje;
                ViewBag.Exito = respuesta.Exito;
                return View(new List<Camion>());
            }
        }
        public ActionResult Mantener(int id = 0)
        {
            if (id != 0)
            {
                var respuesta = servicioTransportista.LeerCamion(id, Login.SesionId);
                if (!respuesta.Exito)
                {
                    return RedirectToAction("Listar", new { respuesta.Mensaje });
                }
                return View(respuesta.Camion);
            }
            else
            {
                return View(new Camion());
            }
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Mantener(Camion camion, string RefrigeraEdit="false")
        {

            camion.Refrigera = RefrigeraEdit.Equals("true");
            if (camion.IdCamion == 0)
            {
                camion.IdUsuario = Login.IdUsuario;
                var respuesta = servicioTransportista.CrearCamion(camion, Login.SesionId);
                ViewBag.Exito = respuesta.Exito;
                ViewBag.Mensaje = respuesta.Mensaje;
                if (!ViewBag.Exito)
                    return View(camion);
                return View(respuesta.Camion);
            }
            else
            {
                var respuesta = servicioTransportista.ModificarCamion(camion, Login.SesionId);
                ViewBag.Exito = respuesta.Exito;
                ViewBag.Mensaje = respuesta.Mensaje;
                if (!ViewBag.Exito)
                    return View(camion);

                return View(respuesta.Camion);
            }
        }
    }
}

FERIA.FRONT/Controllers/SistemaController.cs
using FERIA.CLASES;
using FERIA.FRONT.NEGOCIO;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace FERIA.FRONT.Controllers
{
    [Authorize]
    public class SistemaController : Controller
    {
        ServicioUsuario servicioUsuario;
        Usuario Login = Helper.Autenticacion.TraerUsuarioAutenticado();
        public SistemaController() {
            servicioUsuario = new ServicioUsuario();
        }

        // GET: Sistema
        public ActionResult Index()
        {
            return View();
        }
        [AllowAnonymous]
        public ActionResult CerrarSesion()
        {
            Helper.Autenticacion.DestruirSesionUsuario();
            return RedirectToAction("Login", "Home", new { cerrarSesion = true });
        }
        #region "PERFILES"
        public ActionResult Perfil(bool exito = false, bool error = false, string mensaje = "")
        {
            ViewBag.Exito = exito;
            ViewBag.Error = error;
            ViewBag.Mensaje = mensaje;
            var respuesta = servicioUsuario.Leer(Login.IdUsuario, Login.SesionId );
            if (exito)
            {
                respuesta.Usuario.SesionId = Login.SesionId;
                Helper.Autenticacion.Login(respuesta.Usuario);
            }
            return View(respuesta.Usuario);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Perfil(Usuario usuario)
        {
            if (!string.IsNullOrEmpty(usuario.Clave))
            {
                usuario.Clave = "";
            }

            var respuesta = servicioUsuario.Modificar(usuario, Login.SesionId);
            if (respuesta.Exito)
            {
                ViewBag.Exito = true;
                ViewBag.Mensaje = "Se ha modificado correctamente";
            }
            else
            {
                ViewBag.Error = true;
                ViewBag.Mensaje = respuesta.Mensaje;
            }
            return RedirectToAction("Perfil", new { exito = ViewBag.Exito, error = ViewBag.Error, mensaje = ViewBag.Mensaje });

        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult PerfilClave(Usuario usuario)
        {

            usuario.Clave = NEGOCIO.Funciones.Encripta.EncodePassword(usuario.Clave);
            usuario.ReClave = NEGOCIO.Funciones.Encripta.EncodePassword(usuario.ReClave);

            var respuesta = servicioUsuario.ModificarClave(usuario, Login.SesionId);
            if (respuesta.Exito)
            {
                ViewBag.Exito = true;
                ViewBag.Mensaje = "Se ha modificado la clave correctamente";
            }
            else
            {
                ViewBag.Error = true;
                ViewBag.Mensaje = respuesta.Mensaje;
            }
            return RedirectToAction("Perfil", new { exito = ViewBag.Exito, error = ViewBag.Error, mensaje = ViewBag.Mensaje });
        }
        #endregion
    }
}

FERIA.FRONT/Views/Camion/Listar.cshtml
@model List<FERIA.CLASES.Camion>
@{
    ViewBag.Title = "Listar Camiones";
    Layout = "~/Views/Shared/_Interno.cshtml";
    if (ViewBag.Exito == null)
    {
        ViewBag.Exito = false;
    }
    if (ViewBag.Mensaje == null)
    {
        ViewBag.Mensaje = "";
    }
}
<div class="row wrapper border-bottom white-bg page-heading">
    <div class="col-lg-10">
        <h2>Camiones</h2>
        <ol class="breadcrumb">
            <li class="breadcrumb-item">
                <a href="@Url.Action("Index", "Sistema")">Inicio</a>
            </li>
            @*<li class="breadcrumb-item">
                    <a>Forms</a>
                </li>*@
            <li class="breadcrumb-item active">
                <strong>Listado de Mis Camiones</strong>
            </li>
        </ol>
    </div>
    <div class="col-lg-2">

    </div>
</div>
<div class="wrapper wrapper-content animated fadeInRight">
    <div class="row">
        <div class="col-lg-12">
            <!--GRILLA DE RESULTADOS-->
            <div class="row">
                <div class="col-lg-12">
                    <button class="btn btn-primary pull-right" type="button" onclick="location.href = '@Url.Action("Mantener", "Camion")'; return false;"><i class="fa fa-plus"></i> <span class="bold">Nuevo Camión</span></button>
                    @if (Model.Count > 0)
                    {
                        <div class="ibox ">
                            <div class="ibox-title">
                                <h5>Resultado de Búsqueda </h5>
                            </div>
                            <div class="ibox-content">
                                <table class="table table-striped table-responsive-lg">
                                    <thead>
                                        <tr>
                                            <th>#</th>
                                            <th>Peso Máximo (KG)</th>
                                            <th>Refrigera</th>
                                            <th>Accion</th>
                                        </tr>
                                    </thead>
                                    <tbody>
                                        @foreach (FERIA.CLASES.Camion item in Model)
                                        {
                                            <tr>
                                                <td>@item.IdCamion </td>
                                                <td>@item.PesoMaximo </td>
                                                <td>@((item.Refrigera) ? "SI": "NO") </td>
                                                <td>
                                                    <button class="btn btn-default btn-circle" title="Editar" type="button" onclick="location.href = '@Url.Action("Mantener", "Camion", new { id = item.IdCamion })'; return false;">
                                                        <i class="fa fa-edit "></i>
                                                    </button>
                                                </td>
                                            </tr>
                                        }
                                    </tbody>
                                </table>
                            </div>
                        </div>
                    }
                    else
                    {
                        <div class="ibox-content">
                            <div class="alert alert-info">
                                No existen Datos
                            </div>
                        </div>
                    }
                </div>
            </div>
        </div>
    </div>
</div>
@section Scripts{
    @if (ViewBag.Mensaje != "")
    {
        <script>
        swal({
            title: ("@ViewBag.Exito" != "False") ? "Felicidades!" :"Error!",
            text: fncReemplazaTilde("@ViewBag.Mensaje"),
            type: ("@ViewBag.Exito" != "False") ? "success" :"error"
        });
        </script>
    }
}

FERIA.FRONT/Views/Camion/Mantener.cshtml
@model FERIA.CLASES.Camion
@{
    ViewBag.Title = "Mantención de Camiones";
    Layout = "~/Views/Shared/_Interno.cshtml";

    //var Login = FERIA.FRONT.Helper.Autenticacion.TraerUsuarioAutenticado();

    ViewBag.Title = (Model.IdCamion == 0) ? "Creación de Camión" : "Modificación de Camión";
    ViewBag.Accion = (Model.IdCamion == 0) ? "Grabar" : "Modificar";


    if (ViewBag.Exito == null)
    {
        ViewBag.Exito = false;
    }
    if (ViewBag.Mensaje == null)
    {
        ViewBag.Mensaje = "";
    }
}
<div class="row wrapper border-bottom white-bg page-heading">
    <div class="col-lg-10">
        <h2>Productor</h2>
        <ol class="breadcrumb">
            <li class="breadcrumb-item">
                <a href="@Url.Action("Index", "Sistema")">Inicio</a>
            </li>
            <li class="breadcrumb-item">
                <a>Camiones</a>
            </li>
            <li class="breadcrumb-item active">
                <strong>@ViewBag.Title</strong>
            </li>
        </ol>
    </div>
    <div class="col-lg-2">

    </div>
</div>
<div class="wrapper wrapper-content animated fadeInRight">
    <div class="row">
        <div class="col-lg-12">
            <form role="form" method="post" action="@Url.Action("Mantener", "Camion")" autocomplete="off">
                @Html.AntiForgeryToken()
                <input type="hidden" name="IdCamion" id="IdCamion" value="@Model.IdCamion" />
                <input type="hidden" name="IdUsuario" id="IdUsuario" value="@Model.IdUsuario" />
                <div class="row">
                    <div class="col-lg-12">
                        <div class="ibox ">
                            <div class="ibox-title">
                                <h5>@ViewBag.Title</h5>
                            </div>
                            <div class="ibox-content">
                                <div class="row">
                                    <div class="col-sm-12">
                                        <h3 class="m-t-none m-b">Datos Camión</h3>
                                        <p>Información del Camión</p>
                                        <div class="form-row">
                                            <div class="form-group col-lg-4">
                                                <label>Peso Máximo (KG)</label>
                                                <input type="number" name="PesoMaximo" id="PesoMaximo" placeholder="Ingrese Peso Máximo" class="form-control" value="@Model.PesoMaximo" required />
                                            </div>
                                            <div class="form-group col-lg-4">
                                                <label>Refrigera</label><br />
                                                <input type="checkbox" name="Refrigera" id="Refrigera" class="js-switch" @((Model.Refrigera) ? "checked" : "") />
                                                <input name="RefrigeraEdit" id="RefrigeraEdit" type="hidden" value="true" />
                                            </div>
                                        </div>
                                    </div>
                                </div>
                                <div class="row">
                                    <div class="col-sm-12">
                                        <div class=" pull-right ">
                                            <button class="btn btn-default" type="button" onclick="location.href = '@Url.Action("Listar", "Camion")';"><i class="fa fa-backward"></i><span class="bold"> Volver</span></button>
                                            <button class="btn btn-primary" type="submit"><i class="fa fa-save"></i><span class="bold"> @ViewBag.Accion</span></button>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </form>
        </div>
    </div>
</div>

@section Scripts{
    <script>
        $(document).ready(function () {
            var elem = document.querySelector('.js-switch');
            var switchery = new Switchery(elem, { color: '#1AB394' });
            $('.switchery').click(function () {
                if (document.getElementById('Refrigera').checked == true) {
                    document.getElementById('RefrigeraEdit').value = 'true'
                }
                else {
                    document.getElementById('RefrigeraEdit').value = 'false'
                }
            });
        });
    </script>

    @if (ViewBag.Mensaje != "")
    {
        <script>

        swal({
            title: ("@ViewBag.Exito" != "False") ? "Felicidades!" :"Error!",
            text: fncReemplazaTilde("@ViewBag.Mensaje"),
            type: ("@ViewBag.Exito" != "False") ? "success" :"error"
        });
        </script>
    }

}