FERIA.FRONT/Controllers/SistemaController.cs
using FERIA.CLASES;
using FERIA.FRONT.NEGOCIO;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace FERIA.FRONT.Controllers
{
    [Authorize]
    public class SistemaController : Controller
    {
        ServicioUsuario servicioUsuario;
        Usuario Login = Helper.Autenticacion.TraerUsuarioAutenticado();
        public SistemaController() {
            servicioUsuario = new ServicioUsuario();
        }

        // GET: Sistema
        public ActionResult Index()
        {
            return View();
        }
        [AllowAnonymous]
        public ActionResult CerrarSesion()
        {
            Helper.Autenticacion.DestruirSesionUsuario();
            return RedirectToAction("Login", "Home", new { cerrarSesion = true });
        }
        #region "PERFILES"
        public ActionResult Perfil(bool exito = false, bool error = false, string mensaje = "")
        {
            ViewBag.Exito = exito;
            ViewBag.Error = error;
            ViewBag.Mensaje = mensaje;
            var respuesta = servicioUsuario.Leer(Login.IdUsuario, Login.SesionId );
            if (exito)
            {
                respuesta.Usuario.SesionId = Login.SesionId;
                Helper.Autenticacion.Login(respuesta.Usuario);
            }
            return View(respuesta.Usuario);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Perfil(Usuario usuario)
        {
            if (!string.IsNullOrEmpty(usuario.Clave))
            {
                usuario.Clave = "";
            }

            var respuesta = servicioUsuario.Modificar(usuario, Login.SesionId);
            if (respuesta.Exito)
            {
                ViewBag.Exito = true;
                ViewBag.Mensaje = "Se ha modificado correctamente";
            }
            else
            {
                ViewBag.Error = true;
                ViewBag.Mensaje = respuesta.Mensaje;
            }
            return RedirectToAction("Perfil", new { exito = ViewBag.Exito, error = ViewBag.Error, mensaje = ViewBag.Mensaje });

        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult PerfilClave(Usuario usuario)
        {

            usuario.Clave = NEGOCIO.Funciones.Encripta.EncodePassword(usuario.Clave);
            usuario.ReClave = NEGOCIO.Funciones.Encripta.EncodePassword(usuario.ReClave);

            var respuesta = servicioUsuario.ModificarClave(usuario, Login.SesionId);
            if (respuesta.Exito)
            {
                ViewBag.Exito = true;
                ViewBag.Mensaje = "Se ha modificado la clave correctamente";
            }
            else
            {
                ViewBag.Error = true;
                ViewBag.Mensaje = respuesta.Mensaje;
            }
            return RedirectToAction("Perfil", new { exito = ViewBag.Exito, error = ViewBag.Error, mensaje = ViewBag.Mensaje });
        }
        #endregion
    }
}

FERIA.FRONT/Controllers/SubastaController.cs
using FERIA.CLASES;
using FERIA.FRONT.NEGOCIO;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace FERIA.FRONT.Controllers
{
    [Authorize(Roles = "5")]
    public class SubastaController : Controller
    {   
        ServicioSubasta servicioSubasta;
        ServicioTransportista servicioTransportista;
        Usuario Login = Helper.Autenticacion.TraerUsuarioAutenticado();
        public SubastaController()
        {
            servicioSubasta = new ServicioSubasta();
            servicioTransportista = new ServicioTransportista();
        }

        // GET: Subasta
        public ActionResult Participar(string mensaje = "", bool exito = false)
        {
            if (!string.IsNullOrEmpty(mensaje))
            {
                ViewBag.Exito = exito;
                ViewBag.Mensaje = mensaje;
            }
            var respuesta = servicioSubasta.ListarActivas(Login.SesionId);
            if (respuesta.Exito)
                return View(respuesta.Subastas);
            else
            {
                ViewBag.Mensaje = respuesta.Mensaje;
                ViewBag.Exito = respuesta.Exito;
                return View(new List<Subasta>());
            }
        }
        public ActionResult Listar(string mensaje = "", bool exito = false)
        {
            if (!string.IsNullOrEmpty(mensaje))
            {
                ViewBag.Exito = exito;
                ViewBag.Mensaje = mensaje;
            }
            var respuesta = servicioTransportista.ListarSubastasByIdUsuario(Login.IdUsuario, Login.SesionId);
            if (respuesta.Exito)
                return View(respuesta.Subastas);
            else
            {
                ViewBag.Mensaje = respuesta.Mensaje;
                ViewBag.Exito = respuesta.Exito;
                return View(new List<Subasta>());
            }
        }

        [HttpGet]
        public ActionResult Ofertar(int id, string mensaje = "")
        {
            if (!string.IsNullOrEmpty(mensaje))
            {
                ViewBag.Exito = false;
                ViewBag.Mensaje = mensaje;
            }
            var respuesta = servicioSubasta.Leer(id, Login.SesionId);
            if (respuesta.Exito)
            {
                return View(respuesta.Subasta);
            }
            else
            {
                ViewBag.Mensaje = respuesta.Mensaje;
                ViewBag.Exito = respuesta.Exito;
                return View("Participar", new List<Subasta>());
            }
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Ofertar(DetalleSubasta detalleSubasta)
        {
            if (detalleSubasta.MontoOferta.Equals(0)) 
            {
                return RedirectToAction("Ofertar", new { id=detalleSubasta.IdSubasta, mensaje= "Monto Oferta no puede ser 0" });
            }
           
            var respuesta = servicioSubasta.Ofertar(detalleSubasta, Login.SesionId);
            if (respuesta.Exito)
            {
                return RedirectToAction("Participar", new { exito = true, mensaje = "Oferta realizada con éxito" });
            }
            else
            {
                var respuesta1 = servicioSubasta.Leer(detalleSubasta.IdSubasta, Login.SesionId);
                ViewBag.Mensaje = respuesta.Mensaje;
                ViewBag.Exito = respuesta.Exito;
                return View(respuesta1.Subasta);
            }
        }

    }
}

FERIA.FRONT/Views/Subasta/Listar.cshtml
@model List<FERIA.CLASES.Subasta>
@{
    var Login = FERIA.FRONT.Helper.Autenticacion.TraerUsuarioAutenticado();
    ViewBag.Title = "Participar";
    Layout = "~/Views/Shared/_Interno.cshtml";
    if (ViewBag.Exito == null)
    {
        ViewBag.Exito = false;
    }
    if (ViewBag.Mensaje == null)
    {
        ViewBag.Mensaje = "";
    }
    var servicioProceso = new FERIA.FRONT.NEGOCIO.ServicioProceso();

}
<div class="row wrapper border-bottom white-bg page-heading">
    <div class="col-lg-10">
        <h2>Mis Subastas</h2>
        <ol class="breadcrumb">
            <li class="breadcrumb-item">
                <a href="@Url.Action("Index", "Sistema")">Inicio</a>
            </li>
            @*<li class="breadcrumb-item">
                    <a>Forms</a>
                </li>*@
            <li class="breadcrumb-item active">
                <strong>Mis Postulaciones</strong>
            </li>
        </ol>
    </div>
    <div class="col-lg-2">

    </div>
</div>
<div class="wrapper wrapper-content animated fadeInRight">
    <div class="row">
        <div class="col-lg-12">
            <!--GRILLA DE RESULTADOS-->
            <div class="row">
                <div class="col-lg-12">
                    @if (Model.Count > 0)
                    {
                        <div class="ibox ">
                            <div class="ibox-title">
                                <h5>Resultado de Búsqueda </h5>
                            </div>
                            <div class="ibox-content">
                                <table class="table table-striped table-responsive-lg">
                                    <thead>
                                        <tr>
                                            <th>#</th>
                                            <th>Fecha Inicio</th>
                                            <th>Fecha Termino</th>
                                            <th>Kilos</th>
                                            <th>Ofertas</th>
                                            <th>Estado Subasta</th>
                                            <th>Accion</th>
                                        </tr>
                                    </thead>
                                    <tbody>
                                        @foreach (FERIA.CLASES.Subasta item in Model)
                                        {
                                            var proceso = servicioProceso.Leer(item.IdProceso, Login.SesionId);
                                            int Kilos = 0;
                                            if (proceso.Exito)
                                            {
                                                Kilos = proceso.Proceso.Orden.DetalleOrden.Sum(x => x.Cantidad);
                                            }
                                            <tr>
                                                <td>@item.IdSubasta </td>
                                                <td>@item.FechaSubasta.ToString("dd-MM-yyyy") </td>
                                                <td>@item.FechaTermino.ToString("dd-MM-yyyy") </td>
                                                <td>@Kilos.ToString("#0,00")  </td>
                                                <td>@item.DetalleSubasta.Count </td>
                                                <td>@((item.Estado) ? "Activo":"Inactivo") </td>
                                                <td>
                                                    <button class="btn btn-primary btn-circle" title="ver detalle subasta" type="button"  data-toggle="modal" href="#modal-form" onclick="fncDetalle('@item.IdSubasta');">
                                                        <i class="fa fa-list"></i>
                                                    </button>
                                                </td>
                                            </tr>
                                        }
                                    </tbody>
                                </table>
                            </div>
                        </div>
                    }
                    else
                    {
                        <div class="ibox-content">
                            <div class="alert alert-info">
                                No existen Datos
                            </div>
                        </div>
                    }
                </div>
            </div>
        </div>
    </div>
</div>
<div id="modal-form" class="modal" style="z-index:10000!important;" aria-hidden="true" tabindex="-1">
    <div class="modal-dialog modal-lg">
        <div class="modal-content">
            <div class="modal-body">
                <div id="Datos">
                </div>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-white" data-dismiss="modal">Cerrar</button>
            </div>
        </div>
    </div>
</div>
@section Scripts{
    <script>
        function fncDetalle(vIdSubasta)
        {
            $.ajax({
                url: '@Url.Content("~/Utils/DetalleSubasta")?_idSubasta=' + vIdSubasta,
                    type: 'GET',
                    data: "",
                    contentType: 'application/json; charset=utf-8',
                    beforeSend: function(s, e) {
                        $("#Datos").html("<img src=\"../../Imagen/loading.gif\" /><br />Procesando la información..");
                    },
                    success: function (data) {
                        $("#Datos").html(data);
                        if ($("#Datos").val() == null) {
                            $("#Datos").html("No fue posible obtener los datos");
                        }
                    },
                    error: function (s, e) {
                        $("#Datos").html("Ha ocurrido un error al momento de obtener los datos");
                    }
                });
        }
    </script>
    @if (ViewBag.Mensaje != "")
    {
        <script>
        swal({
            title: ("@ViewBag.Exito" != "False") ? "Felicidades!" :"Error!",
            text: fncReemplazaTilde("@ViewBag.Mensaje"),
            type: ("@ViewBag.Exito" != "False") ? "success" :"error"
        });
        </script>
    }
}

FERIA.FRONT/Views/Subasta/Ofertar.cshtml
@model FERIA.CLASES.Subasta
@{
    ViewBag.Title = "Ofertar en Subasta";
    Layout = "~/Views/Shared/_Interno.cshtml";
    if (ViewBag.Exito == null)
    {
        ViewBag.Exito = false;
    }
    if (ViewBag.Mensaje == null)
    {
        ViewBag.Mensaje = "";
    }
    FERIA.FRONT.NEGOCIO.ServicioProducto servicioProducto = new FERIA.FRONT.NEGOCIO.ServicioProducto();
    FERIA.FRONT.NEGOCIO.ServicioProceso servicioProceso = new FERIA.FRONT.NEGOCIO.ServicioProceso();
    FERIA.CLASES.Usuario Login = FERIA.FRONT.Helper.Autenticacion.TraerUsuarioAutenticado();
    var productos = servicioProducto.Listar(Login.IdUsuario, Login.SesionId);
    var proceso = servicioProceso.Leer(Model.IdProceso, Login.SesionId).Proceso;
    var ganadas = proceso.Ofertas.Where(x => x.Estado.Equals("GANADA")).ToList();
     

}
<div class="row wrapper border-bottom white-bg page-heading">
    <div class="col-lg-10">
        <h2>Ofertar en Subasta</h2>
        <ol class="breadcrumb">
            <li class="breadcrumb-item">
                <a href="@Url.Action("Index", "Sistema")">Inicio</a>
            </li>
            @*<li class="breadcrumb-item">
                    <a>Forms</a>
                </li>*@
            <li class="breadcrumb-item active">
                <strong>Ofertando en Proceso</strong>
            </li>
        </ol>
    </div>
    <div class="col-lg-2">

    </div>
</div>
<div class="wrapper wrapper-content animated fadeInRight">
    <div class="row">
        <div class="col-lg-12">
            <form role="form" name="frmOferta" id="frmOferta" method="post" action="@Url.Action("Ofertar", "Subasta", new FERIA.CLASES.DetalleSubasta())" autocomplete="off">
                @Html.AntiForgeryToken()
                <input type="hidden" name="IdSubasta" id="IdSubasta" value="@Model.IdSubasta" />
                <input type="hidden" name="IdUsuario" id="IdUsuario" value="@Login.IdUsuario" />
                <div class="row">
                    <div class="col-lg-12">
                        <div class="ibox ">
                            <div class="ibox-title">
                                <h5>@ViewBag.Title</h5>
                            </div>
                            <div class="ibox-content">
                                <div class="row">
                                    <div class="col-sm-12">
                                        <h3 class="m-t-none m-b">Datos de la Subasta</h3>
                                        <div class="form-row">
                                            <div class="form-group col-lg-4">
                                                <label>Fecha Inicio</label>
                                                <input type="text" name="FechaProceso" id="FechaProceso" class="form-control disabled" readonly value="@Model.FechaSubasta.ToString("dd/MM/yyyy")" required />
                                            </div>
                                            <div class="form-group col-lg-4">
                                                <label>Fecha Termino</label>
                                                <input type="text" name="FechaFinProceso" id="FechaFinProceso" class="form-control disabled" readonly value="@Model.FechaTermino.ToString("dd/MM/yyyy")" required />
                                            </div>
                                            <div class="form-group col-lg-4">
                                                <label>N° Subasta</label>
                                                <input type="text" name="IdOrden" id="IdOrden" class="form-control disabled" readonly value="@Model.IdSubasta" required />
                                            </div>
                                        </div>
                                        <div class="form-row">
                                            <div class="form-group col-lg-4">
                                                <label>Tipos de Productos</label>
                                                <input type="text" name="Tipos" id="Tipos" class="form-control disabled" readonly value="@proceso.Orden.DetalleOrden.Count" required />
                                            </div>
                                            <div class="form-group col-lg-4">
                                                <label>Cantidad Total (KG)</label>
                                                <input type="text" name="Cantidad" id="Cantidad" class="form-control disabled" readonly value="@proceso.Orden.DetalleOrden.Sum(x => x.Cantidad).ToString("#0,00")" required />
                                            </div>
                                        </div>
                                    </div>
                                </div>
                                <div class="row">
                                    <div class="col-sm-12">
                                        <h3 class="m-t-none m-b">Detalle del Pedido</h3>
                                        <table class="table table-striped table-responsive-lg">
                                            <thead>
                                                <tr>
                                                    <th>Categoría</th>
                                                    <th>Cantidad Requerida (KG)</th>
                                                </tr>
                                            </thead>
                                            <tbody>
                                                @{
                                                    foreach (var item in proceso.Orden.DetalleOrden)
                                                    {
                                                        <tr>
                                                            <td>@item.NombreCategoria (@item.NombreIngles)</td>
                                                            <td>@item.Cantidad.ToString("#0,00")</td>
                                                        </tr>
                                                    }
                                                }
                                            </tbody>
                                        </table>
                                        <table class="table table-striped table-responsive-lg">
                                            <thead>
                                                <tr>
                                                    <th>Dirección</th>
                                                    <th>Región</th>
                                                    <th>Comuna</th>
                                                </tr>
                                            </thead>
                                            <tbody>
                                                @{
                                                    var servicio = new FERIA.FRONT.NEGOCIO.ServicioUsuario();
                                                    foreach (var item in ganadas)
                                                    {
                                                        var productor = servicio.LeerProductor(item.IdUsuario, Login.SesionId).Usuario;
                                                        var comuna = FERIA.FRONT.UtilConfig.Comunas().Where(x => x.IdComuna.Equals(productor.IdComuna)).FirstOrDefault();
                                                        <tr>
                                                            <td>@productor.Direccion</td>
                                                            <td>@comuna.NombreRegion</td>
                                                            <td>@comuna.NombreComuna</td>
                                                        </tr>
                                                    }
                                                }
                                            </tbody>
                                        </table>
                                    </div>
                                </div>
                                <div class="row">
                                    <div class="col-sm-12">
                                        <h3 class="m-t-none m-b">Mi Oferta</h3>
                                        <div class="form-row">
                                            <div class="form-group col-lg-4">
                                                <label>Monto Oferta ($ PESOS) <i class="fa fa-money"></i></label>
                                                <input type="number" name="MontoOferta" id="MontoOferta" class="form-control" value="0" required />
                                            </div>
                                        </div>
                                    </div>
                                </div>
                                <div class="row">
                                    <div class="col-sm-12">
                                        <div class=" pull-right ">
                                            <button class="btn btn-default" type="button" onclick="location.href = '@Url.Action("Participar", "Subasta")';"><i class="fa fa-backward"></i><span class="bold"> Volver</span></button>
                                            <button class="btn btn-primary" type="button" onclick="fncSubmit();"><i class="fa fa-send"></i><span class="bold"> Enviar Oferta</span></button>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </form>
        </div>
    </div>
</div>
@section Scripts{
    <script>
        function fncSubmit() {
            swal({
                title: "¿Confirma la operación?",
                text: "Esta a punto de enviar una oferta a la subasta seleccionada ¿Desea continuar?",
                type: "info",
                showCancelButton: true,
                confirmButtonColor: "#DD6B55",
                confirmButtonText: "Confirmar",
                closeOnConfirm: false
            }, function (isConfirm) {
                if (isConfirm) {
                    swal.close();
                    $("#loading").show();
                    document.frmOferta.submit();
                }
            });
        }
    </script>
    @if (ViewBag.Mensaje != "")
    {
        <script>
        swal({
            title: ("@ViewBag.Exito" != "False") ? "Felicidades!" :"Error!",
            text: fncReemplazaTilde("@ViewBag.Mensaje"),
            type: ("@ViewBag.Exito" != "False") ? "success" :"error"
        });
        </script>
    }

}

FERIA.FRONT/Views/Subasta/Participar.cshtml
@model List<FERIA.CLASES.Subasta>
@{
    var Login = FERIA.FRONT.Helper.Autenticacion.TraerUsuarioAutenticado();
    ViewBag.Title = "Participar";
    Layout = "~/Views/Shared/_Interno.cshtml";
    if (ViewBag.Exito == null)
    {
        ViewBag.Exito = false;
    }
    if (ViewBag.Mensaje == null)
    {
        ViewBag.Mensaje = "";
    }
}
<div class="row wrapper border-bottom white-bg page-heading">
    <div class="col-lg-10">
        <h2>Procesos en Subasta</h2>
        <ol class="breadcrumb">
            <li class="breadcrumb-item">
                <a href="@Url.Action("Index", "Sistema")">Inicio</a>
            </li>
            @*<li class="breadcrumb-item">
                    <a>Forms</a>
                </li>*@
            <li class="breadcrumb-item active">
                <strong>Listado de Subastas Activas</strong>
            </li>
        </ol>
    </div>
    <div class="col-lg-2">

    </div>
</div>
<div class="wrapper wrapper-content animated fadeInRight">
    <div class="row">
        <div class="col-lg-12">
            <!--GRILLA DE RESULTADOS-->
            <div class="row">
                <div class="col-lg-12">
                    @if (Model.Count > 0)
                    {
                        <div class="ibox ">
                            <div class="ibox-title">
                                <h5>Resultado de Búsqueda </h5>
                            </div>
                            <div class="ibox-content">
                                <table class="table table-striped table-responsive-lg">
                                    <thead>
                                        <tr>
                                            <th>#</th>
                                            <th>Fecha Inicio</th>
                                            <th>Fecha Termino</th>
                                            <th>Kilos</th>
                                            <th>Ofertas</th>
                                            <th>Accion</th>
                                        </tr>
                                    </thead>
                                    <tbody>
                                        @foreach (FERIA.CLASES.Subasta item in Model)
                                        {
                                            var proceso = new FERIA.FRONT.NEGOCIO.ServicioProceso().Leer(item.IdProceso, Login.SesionId);
                                            int Kilos = 0;
                                            if (proceso.Exito) {
                                                Kilos = proceso.Proceso.Orden.DetalleOrden.Sum(x => x.Cantidad);
                                            }
                                        <tr>
                                            <td>@item.IdSubasta </td>
                                            <td>@item.FechaSubasta.ToString("dd-MM-yyyy") </td>
                                            <td>@item.FechaTermino.ToString("dd-MM-yyyy") </td>
                                            <td>@Kilos.ToString("#0,00")  </td>
                                            <td>@item.DetalleSubasta.Count </td>
                                            <td>
                                                <button class="btn btn-primary btn-circle" title="Ofertar a Subasta" type="button" onclick="location.href = '@Url.Action("Ofertar", "Subasta", new { id = item.IdSubasta })'; return false;">
                                                    <i class="fa fa-upload"></i>
                                                </button>
                                            </td>
                                        </tr>
                                        }
                                    </tbody>
                                </table>
                            </div>
                        </div>
                    }
                    else
                    {
                        <div class="ibox-content">
                            <div class="alert alert-info">
                                No existen Datos
                            </div>
                        </div>
                    }
                </div>
            </div>
        </div>
    </div>
</div>
@section Scripts{
    @if (ViewBag.Mensaje != "")
    {
        <script>
        swal({
            title: ("@ViewBag.Exito" != "False") ? "Felicidades!" :"Error!",
            text: fncReemplazaTilde("@ViewBag.Mensaje"),
            type: ("@ViewBag.Exito" != "False") ? "success" :"error"
        });
        </script>
    }
}